### PR TITLE
Add Ekleog to the reviewer team

### PR DESCRIPTION
**Pull request by timokau**
https://github.com/timokau/marvin-mk2/issues/34#issuecomment-732306385

### CODE REVIEW

**Review by Ekleog — APPROVED** [review]
Great, thank you! (For your reply on the other thread too, it explains very well, I'm saying it here to not clutter and leave it there as the last message for easy reference :))

**Comment by timokau** [comment]
You're welcome, I'm happy it helped :)

**Comment by Ekleog** [comment]
Hmm it's weird, I haven't seen any notification from marvin yet, despite the fact that [the latest PR that involves me](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+involves%3Aekleog) was more than a week ago.

Was marvin re-deployed since this change, or is it possible that it's currently broken? Or is it possible that there are just not enough PRs that are marvin-enabled? (in which case I guess it'd mean that it may be time to consider auto-enabling it for eg. 1% of all new incoming PRs, if it currently has such a high success rate in practice despite whatever shortcomings it may have left)

**Comment by Ekleog** [comment]
Oh, or another idea: if the rate of incoming PRs is just lower than the rate of PR acceptance of people above me in the list, maybe it'd make sense to just shuffle the list of reviewers before trying to find a reviewer to assign the PR to? (not sure whether it's worth filing an issue for such an improvement yet, as it may be completely unrelated to the point at hand)

**Comment by timokau** [comment]
> Hmm it's weird, I haven't seen any notification from marvin yet, despite the fact that [the latest PR that involves me](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+involves%3Aekleog) was more than a week ago.

Marvin looks for PRs which were updated within the time frame, not just those that were opened. So it is something like [this](https://github.com/NixOS/nixpkgs/issues?q=involves%3Aekleog+updated%3A%3E%3D2020-11-28+-merged%3A%3C2020-12-01) query, which would be 3 PRs.

> Was marvin re-deployed since this change, or is it possible that it's currently broken?

Yes, it was deployed: https://github.com/nix-community/infra/commit/7b07e215121a67277240f7aaaf4973d3c2ef6c2b

> Or is it possible that there are just not enough PRs that are marvin-enabled? (in which case I guess it'd mean that it may be time to consider auto-enabling it for eg. 1% of all new incoming PRs, if it currently has such a high success rate in practice despite whatever shortcomings it may have left)

That's it :) It used to hover around ~10-20 `needs_reviewer` PRs, but right now its 0. It assigned reviewers to two PRs yesterday, otherwise the [queue](https://github.com/NixOS/nixpkgs/labels/needs_reviewer) is currently empty. [Here](https://github.com/NixOS/nixpkgs/issues?q=label%3Amarvin+sort%3Aupdated-desc) are all the marvin-managed PRs.

As I said, this is unusual though. I think its probably in part because of some drive-by reviews triggered by [this](https://discourse.nixos.org/t/misuse-of-commit-permissions/10071/36?u=timokau), and in part due to SuperSandro2000's current attack on the backlog in general :smile:

**Comment by timokau** [comment]
> Oh, or another idea: if the rate of incoming PRs is just lower than the rate of PR acceptance of people above me in the list, maybe it'd make sense to just shuffle the list of reviewers before trying to find a reviewer to assign the PR to?

It already works that way: https://github.com/timokau/marvin-mk2/blob/34c1b7fa98dd48044c4819f84f5fc98617a8c49b/marvin/team.py#L155

For example

```
Nov 30 11:29:22 marvin-mk2: Selecting reviewer from candidates: ['turion', 'symphorien', 'bennyandresen', 'kisik21', 'timokau', 'fgaz', 'Ekleog', 'glittershark', 'kevincox']
Nov 30 11:29:22 marvin-mk2: Testing timokau
Nov 30 11:29:25 marvin-mk2: Limit (1/1d) exceeded until 2020-12-01 10:15:04+00:00.
Nov 30 11:29:25 marvin-mk2: Testing kevincox
Nov 30 11:29:29 marvin-mk2: Limit (7/7d) exceeded until 2020-12-02 07:15:29+00:00.
Nov 30 11:29:29 marvin-mk2: Testing bennyandresen
Nov 30 11:29:32 marvin-mk2: Requesting review from bennyandresen for #82584.
```

**Comment by Ekleog** [comment]
Got it, thank you! It's right that the message you linked is also the one that made me discover marvin :) 

Just to check I understood correctly what you meant, when you linked my “involves” as seen by marvin, you forgot `is:pr` which would result in [1 PR](https://github.com/NixOS/nixpkgs/pulls?q=involves%3Aekleog+is%3Apr+updated%3A%3E%3D2020-11-28+-merged%3A%3C2020-12-01)… am I understanding correctly? Or does marvin also count issues as counting against the rate limit?

**Comment by timokau** [comment]
> Or does marvin also count issues as counting against the rate limit?

It does, although you could argue that it shouldn't. It's kind of in line with the intention of estimating the total "nixpkgs notification load", but it is probably not the behavior you would intuitively expect. You can see the exact query here: https://github.com/timokau/marvin-mk2/blob/34c1b7fa98dd48044c4819f84f5fc98617a8c49b/marvin/team.py#L56

**Comment by Ekleog** [comment]
Got it, thank you! I've just opened #102 with ideas for potential improvements, though I don't think it's any kind of emergency and putting the current marvin algorithm in production is much more important :)

**Comment by timokau** [comment]
Thanks, always nice to hear encouragement :)

**Pull request merged**
